config/routes.rb
Rails.application.routes.draw do
  
  resources :people
  
  
  
  get '/home', to: 'people#home'
  
  get '/fact', to: 'people#fact'
  
  get '/feed', to: 'people#feed'
  
  root 'people#home'
  

end

app/models/person.rb
class Person < ActiveRecord::Base

validates :name, presence: true
validates :weight, presence: true

validates :height, presence: true
validates :color, presence: true

validates :handedness, presence: true
validates :writeStyle, presence: true

validates :writeFont, presence: true
validates :writeColor, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]


  helper_method :home
  def home
       @people = Person.all
  end

  helper_method :fact
  def fact
       @people = Person.all
  end     
  
  helper_method :feed
  def feed
       @people = Person.all
  end     


  # all entries (Person model) inside database called people
  def index
    @people = Person.all
  end



  # view one particular entry (Person model); recorded by id
  def show
  end



  # create new entry (Person model)
  def new
    @person = Person.new
  end



  # what we actually define when we -> create new entry (Person model)
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end



  # edit entry (Person model)
  def edit
  end



  # what we actually define when we -> edit entry (Person model)
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end



  # remove an entry (Person model)
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :weight, :height, :color, :handedness, :writeStyle, :writeFont, :writeColor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment2CMPT276</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= yield %> 

</body>
</html>

app/views/people/_form.html.erb
<div class="indexbody">  <!-- template body -->
 
<style>
  img{
       width: 100%;
       height: auto;
  }
</style>

<div class="picfix">
<img src="/assets/robothandphotoshopnew.png" width="600" height="200">
<p class="title">Hands of CMPT</p>
<p class="title1">"Statistics that you can see!"</p>

<div id="indexbodycontent2">




<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.select :color, ['red','orange','yellow','green','teal','blue','cyan','pink','purple','grey','white']  %>
  </div>
  <div class="field">
    <%= f.label :handedness %><br>
    <%= f.select :handedness, ['right','left','center'] %>  <!-- setting restrictions -->
  </div>
  <div class="field">
    <%= f.label :writeStyle %><br>
    <%= f.select :writeStyle, ['normal','italic'] %>
  </div>
  <div class="field">
    <%= f.label :writeFont %><br>
    <%= f.select :writeFont, ['times new roman','georgia','arial','helvetica','impact','tahoma','verdana'] %>
  </div>
  <div class="field">
    <%= f.label :writeColor %><br>
    <%= f.select :writeColor, ['red','orange','yellow','green','teal','blue','cyan','pink','purple','grey','white']  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Cancel', people_path %>

</div>

</div>

</div>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>  <!-- ruby action for precontrollers -->

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/fact.html.erb
<div class="indexbody">  <!-- used as a template -->
 
<style>
  img{
       width: 100%;
       height: auto;
  }
</style>

<div class="picfix">
<img src="/assets/robothandphotoshopnew.png" width="600" height="200">
<p class="title">Hands of CMPT</p>
<p class="title1">"Statistics that you can see!"</p>
<p class="title2"><%= link_to 'Home', '/home', {style: "color: white"} %></p>
<p class="title3"><%= link_to 'Data', people_path, {style: "color: white"} %></p>
<p class="title5" id="title55"><%= link_to 'Fact', '/fact', {style: "color: white"} %></p>
<p class="title6"><%= link_to 'Feed', '/feed', {style: "color: white"} %></p>


<div class="borderplace">
     <h2>Fact</h2>
</div>



<div class="indexbodycontentborder">

  
</div>



<div class="indexbodycontent">
  
  

     <% @people.each do |person| %>    <!-- display data verbally -->
        
        <% if person.writeStyle == "italic" %>
            <em><p style="display: inline"><span style="color:#FFFF00"><%= person.name %></span> <span style="color:#FFFF00">weighs <%= person.weight %> pounds</span> and is <span style="color:#FFFF00"><%= person.height %>cm tall</span>.</p></em><br>
            <em><p style="display: inline">This individual's <span style="color:#FFFF00">favorite color is <%= person.color %></span> and their <span style="color:#FFFF00">favorite writing color is <%= person.writeColor %></span>.</p></em><br>
            <em><p style="display: inline">In addition they're <span style="color:#FFFF00"><%= person.handedness %> handed</span> and prefers to <span style="color:#FFFF00">write in <%= person.writeFont %> font</span> with a <span style="color:#FFFF00"><%= person.writeStyle %> style</span>.</p></em><br>


            <% if person.handedness == "left" %>   <!-- statistical data for handedness -->
                      <% l=0 %>
                      <% @people.each do |person| %>
                          <% if person.handedness == "left" %>
                             <% l=l+1 %>
                          <% end %>    
                      <% end %> 
                      <p style="color:#0EBFE9">Contributing to 1/<%= l %> of left handers.</p> 
            <% end %>  
            
            
            <% if person.handedness == "right" %>
                      <% r=0 %>
                      <% @people.each do |person| %>
                          <% if person.handedness == "right" %>
                             <% r=r+1 %>
                          <% end %>    
                      <% end %> 
                      <p style="color:#0EBFE9">Contributing to 1/<%= r %> of right handers.</p> 
            <% end %>  
            
            
            <% if person.handedness == "center" %>
                      <% c=0 %>
                      <% @people.each do |person| %>
                          <% if person.handedness == "center" %>
                             <% c=c+1 %>
                          <% end %>    
                      <% end %> 
                      <p style="color:#0EBFE9">Contributing to 1/<%= c %> of center handers (can use both hands).</p> 
            <% end %>              
            
            
            <p class="shitty" style="background-color: <%= person.color %>; width: <%= person.weight %>px; height: <%= person.height %>px;" align="<%= person.handedness %>"><font color=<%= person.writeColor %> face=<%= person.writeFont %>><em><%= person.name %></em></font></p>                                         
            <br></br>
        <% else %>     <!-- for the non-italic case -->
            <em><p style="display: inline"><span style="color:#FFFF00"><%= person.name %></span> <span style="color:#FFFF00">weighs <%= person.weight %> pounds</span> and is <span style="color:#FFFF00"><%= person.height %>cm tall</span>.</p></em><br>
            <em><p style="display: inline">This individual's <span style="color:#FFFF00">favorite color is <%= person.color %></span> and their <span style="color:#FFFF00">favorite writing color is <%= person.writeColor %></span>.</p></em><br>
            <em><p style="display: inline">In addition they're <span style="color:#FFFF00"><%= person.handedness %> handed</span> and prefers to <span style="color:#FFFF00">write in <%= person.writeFont %> font</span> with a <span style="color:#FFFF00"><%= person.writeStyle %> style</span>.</p></em><br>


            <% if person.handedness == "left" %>
                      <% l=0 %>
                      <% @people.each do |person| %>
                          <% if person.handedness == "left" %>
                             <% l=l+1 %>
                          <% end %>    
                      <% end %> 
                      <p style="color:#0EBFE9">Contributing to 1/<%= l %> of left handers.</p> 
            <% end %>  
            
            
            <% if person.handedness == "right" %>
                      <% r=0 %>
                      <% @people.each do |person| %>
                          <% if person.handedness == "right" %>
                             <% r=r+1 %>
                          <% end %>    
                      <% end %> 
                      <p style="color:#0EBFE9">Contributing to 1/<%= r %> of right handers.</p> 
            <% end %>  
            
            
            <% if person.handedness == "center" %>
                      <% c=0 %>
                      <% @people.each do |person| %>
                          <% if person.handedness == "center" %>
                             <% c=c+1 %>
                          <% end %>    
                      <% end %> 
                      <p style="color:#0EBFE9">Contributing to 1/<%= c %> of center handers (can use both hands).</p> 
            <% end %>                          
 
            
            <p class="shitty" style="background-color: <%= person.color %>; width: <%= person.weight %>px; height: <%= person.height %>px;" align="<%= person.handedness %>"><font color=<%= person.writeColor %> face=<%= person.writeFont %>><%= person.name %></font></p>
            <br></br>
        <% end %>
        
     <% end %>



   


</div>

</div>

</div>

app/views/people/feed.html.erb
<div class="indexbody">    <!-- act as a template -->
 
<style>
  img{
       width: 100%;
       height: auto;
  }
</style>

<div class="picfix">
<img src="/assets/robothandphotoshopnew.png" width="600" height="200">
<p class="title">Hands of CMPT</p>
<p class="title1">"Statistics that you can see!"</p>
<p class="title2"><%= link_to 'Home', '/home', {style: "color: white"} %></p>
<p class="title3"><%= link_to 'Data', people_path, {style: "color: white"} %></p>
<p class="title5"><%= link_to 'Fact', '/fact', {style: "color: white"} %></p>
<p class="title6" id="title66"><%= link_to 'Feed', '/feed', {style: "color: white"} %></p>


<div class="borderplace">
     <h2>Feed</h2>
</div>



<div class="indexbodycontentborder">

  
</div>


<div class="indexbodycontent">
  
         <p>If you have any comments, suggestions, complaints, please talk to us! Your feedback is highly valued!</p>
         <ul><ul><p>We are located inside the CMPT common room.</p></ul></ul>

</div>



</div>

</div>

app/views/people/home.html.erb
<div class="indexbody">   <!-- act as a template -->
 
<style>
  img{
       width: 100%;
       height: auto;
  }
</style>

<div class="picfix">
<img src="/assets/robothandphotoshopnew.png" width="600" height="200">
<p class="title">Hands of CMPT</p>
<p class="title1">"Statistics that you can see!"</p>
<p class="title2" id="title22"><%= link_to 'Home', '/home', {style: "color: white"} %></p>
<p class="title3"><%= link_to 'Data', people_path, {style: "color: white"} %></p>
<p class="title5"><%= link_to 'Fact', '/fact', {style: "color: white"} %></p>
<p class="title6"><%= link_to 'Feed', '/feed', {style: "color: white"} %></p>




<div class="borderplace">
     <h2>Home</h2>
</div>




<div class="indexbodycontentborder">

  
</div>


<div class="indexbodycontent">

<p>Welcome to Hands of CMPT!</p>
<ul><ul><p>This website is dedicated in gathering hand information from CMPT students.</p></ul></ul>

</div>

</div>

</div>

app/views/people/index.html.erb
<div class="indexbody">      <!-- act as a template -->
 
<style>
  img{
       width: 100%;
       height: auto;
  }
</style>

<div class="picfix">
<img src="/assets/robothandphotoshopnew.png" width="600" height="200">
<p class="title">Hands of CMPT</p>
<p class="title1">"Statistics that you can see!"</p>
<p class="title2"><%= link_to 'Home', '/home', {style: "color: white"} %></p>
<p class="title3" id="title33"><%= link_to 'Data', people_path, {style: "color: white"} %></p>
<p class="title5"><%= link_to 'Fact', '/fact', {style: "color: white"} %></p>
<p class="title6"><%= link_to 'Feed', '/feed', {style: "color: white"} %></p>


<div class="borderplace">
     <h2>Data</h2>
</div>


<div class="indexbodycontentborder">

  
</div>




<div id="indexbodycontent1">     <!-- import data contents here -->

<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Weight</th>
      <th>Height</th>
      <th>Color</th>
      <th>Handedness</th>
      <th>Writestyle</th>
      <th>Writefont</th>
      <th>Writecolor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.weight %></td>
        <td><%= person.height %></td>
        <td><%= person.color %></td>
        <td><%= person.handedness %></td>
        <td><%= person.writeStyle %></td>
        <td><%= person.writeFont %></td>
        <td><%= person.writeColor %></td>
        <td><%= link_to 'Show', person, {style: "color: #00BFFF"} %></td>
        <td><%= link_to 'Edit', edit_person_path(person), {style: "color: #00BFFF"} %></td>
        <td><%= link_to 'Destroy', person, style: "color:#00BFFF" ,method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>     

<%= link_to 'New Person', new_person_path, {style: "color: #C6C3B5"} %>

</div>



</div>

</div>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>    <!-- ruby code for precontroller action -->

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<div class="indexbody">   <!-- template for html pages -->
 
<style>
  img{
       width: 100%;
       height: auto;
  }
</style>

<div class="picfix">
<img src="/assets/robothandphotoshopnew.png" width="600" height="200">
<p class="title">Hands of CMPT</p>
<p class="title1">"Statistics that you can see!"</p>




<div id="indexbodycontent3">   <!-- ruby code for precontroller actions -->








<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @person.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @person.height %>
</p>

<p>
  <strong>Color:</strong>
  <%= @person.color %>
</p>

<p>
  <strong>Handedness:</strong>
  <%= @person.handedness %>
</p>

<p>
  <strong>Writestyle:</strong>
  <%= @person.writeStyle %>
</p>

<p>
  <strong>Writefont:</strong>
  <%= @person.writeFont %>
</p>

<p>
  <strong>Writecolor:</strong>
  <%= @person.writeColor %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>





</div>

</div>

</div>